version: '3.9'
services:
  localstack:
    container_name: localstack_main
    image: localstack/localstack
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
    ports:
      - "127.0.0.1:4566:4566"

  main_interface:
    build:
      context: ./irc
      dockerfile: ./Dockerfile
    container_name: main_interface
    ports:
      - "1337:1337"
    restart: always
